### ISSUE TITLE
Removal of `__init__.py` breaks TOBIAS

### ISSUE THREAD

**Issue by losuler** [art-egorov/svist4get#2]
Was it your intention to create a namespace package[^1]? The reason I'm asking is because I discovered that your removal of `svist4get/__init__.py` in 1.3 broke the `TOBIAS PlotTracks` command[^2], where `svist4get.__file__` now returns `None`.

[^1]: https://stackoverflow.com/a/48804718
[^2]: https://github.com/loosolab/TOBIAS/blob/df1c72f9c0546fa65369e92b9534ed5bb9d885a6/tobias/tools/plot_tracks.py#L55

**Comment by art-egorov** [comment]
Hi!
Oops, of course, it wasn't supposed to be removed, just accidentally wasn't included in the package. Tomorrow I'll publish an updated version with this file.

**Comment by art-egorov** [comment]
Hi again! 
Updated version with the restored file now available in pypi and here 🙂
Thank you very much for this report!
