### ISSUE TITLE
Does setup.py really need argparse?

### ISSUE THREAD

**Issue by aowenson-imm** [art-egorov/svist4get#3]
Python3 has `argparse` package built-in, so nothing needed from PIP. In fact, the latest version on PIP was 2015! Can it be removed from `setup.py`?

**Comment by art-egorov** [comment]
Hi!
Surely it's not needed there, seems it was put accidentally, but it shouldn't affect behaviour of the tool and installation process. 
P.S.
I was writing the tool being a bachelor student..so, even while it works correctly there is a lot of strange solutions in it and it hardly can be called as optimised in any way 🥲

Best

**Comment by aowenson-imm** [comment]
The problem is PIP wants to install the old version of argparse, which will then take precedence over the modern version built into Python 3 today. I had to override PIP (`pip install svist4get --no-deps`).

**Comment by art-egorov** [comment]
I see, i will update it soon
Thanks
